### PR TITLE
[MJARSIGNER-53] - Add support of the "certchain" parameter in JarSigner sign operation

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This adds a new optional parameter for "certchain". If the maintainers are fine with the approach, I will add additional tests.

Downstream pull-request: https://github.com/apache/maven-plugins/pull/125

[MJARSIGNER-53](https://issues.apache.org/jira/browse/MJARSIGNER-53)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@reviewbybees @olamy @aheritier

**Comment by olamy** [comment]
easy I will merge that.
Thanks

**Comment by olamy** [comment]
merged https://svn.apache.org/r1805410

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Pull request closed without merging**
