### PR TITLE
maven-dependency-tree : Resolving reactor deps 2

### PR DESCRIPTION
**Pull request by william-ferguson-au**
Applied changes for https://jira.codehaus.org/browse/MSHARED-336 requested by Herve.

### CODE REVIEW

**Comment by jvanzyl** [comment]
Committed on 1595871

**Comment by hboutemy** [comment]
I made some cleanup after this commit

Now I have 2 question:
1. is it/multi-module-plugin really useful actually? This looks like some experiments, but nothing really useful for the test
1. the overal idea of catching DependencyResolutionException and manually replacing reactor projects inside unresolved dependencies really looks like a hack: reading DefaultMaven source, it seems that the natural way would be more like:

``` try
        {
            Map<String, MavenProject> projectMap;
            projectMap = getProjectMap( session.getProjects() );

            // Desired order of precedence for local artifact repositories
            //
            // Reactor
            // Workspace
            // User Local Repository
            ReactorReader reactorRepository = new ReactorReader( projectMap );

            repoSession.setWorkspaceReader( ChainedWorkspaceReader.newInstance( reactorRepository,
                                                                                repoSession.getWorkspaceReader() ) );
        }
        catch ( org.apache.maven.DuplicateProjectException e )
        {
            return processResult( result, e );
        }``̀`
WDYT?
```

**Comment by william-ferguson-au** [comment]
On Wed, May 21, 2014 at 10:13 AM, Hervé Boutemy notifications@github.comwrote:

> 1. is it/multi-module-plugin really useful actually? This looks like some
>    experiments, but nothing really useful for the test
> 
> It was there so that we could exercise maven-dependency-tree at that point
> in the build life-cycle, ie _before_ any build artifacts had been created
> as this is exactly when we need to be able to resolve the reactor deps for
> the android-maven-plugin.

If you can find another way of exercising maven-dependency-tree at that
build life cycle point that is more appropriate then that's fine. NB I have
come to realise that in order to ensure the multi-module-plugin is built
before multi-module-test on all platforms that the config needs to include:

```
      <setupIncludes>
        <setupInclude>multi-module-plugin/pom.xml</setupInclude>
      </setupIncludes>
```

> 1. the overal idea of catching DependencyResolutionException and
>    manually replacing reactor projects inside unresolved dependencies really
>    looks like a hack: reading DefaultMaven source, it seems that the natural
>    way would be more like:
>    
>    ```
>        ReactorReader reactorRepository = new ReactorReader( projectMap );
>    ```
> 
> It looks reasonable, except that ReactorReader is not public.

**Comment by hboutemy** [comment]
ok, I know understand the idea with multi-module-plugin. Then:
1. IMHO, it should be renamed, with a better description in its pom
2. we should have some tests for its result, since actually, IIUC, you check by hand (and are the only one knowing what you're lokking for :) )

for ReactorReader, it is available in the session, so resolution should happen, or I don't understand the intent (in Maven core). Then we shouldn't need the new method you had to add to graph the dependency tree with reactor content. Did you try to see why reactor content isn't found?

**Comment by william-ferguson-au** [comment]
1. A better description perhaps. This is the current one "Creates a
   maven-plugin that can be used to verify that maven-dep-tree resolves deps
   that only exist within the reactor.". I can't think of anything better.
2. No. I'm not checking by hand. If the multi-module-test (now the reactor)
   project performs all of its ITs then the test succeeds. If the reactor deps
   can't be resolved then the reactor project build breaks and the test fails.

Wrt RectorReader it is not about resolution. The ReactorReader class is not
public, nor is its constructor. So that code cannot compile.

**Comment by hboutemy** [comment]
verify.bsh checks module-z-deps-y/target/tree.txt against expected-tree.txt: ok for the check that reactor deps are resolved with the modification
but the multi-module-plugin outputs content to build.log that is checked nowhere AFAIK:

``` [DEBUG]
[INFO] ResolveDependenciesLifecycleParticipant#afterProjectsRead
[DEBUG] 
[DEBUG] 
[DEBUG] project=org.apache.maven.its.dependency-tree:module-x:jar:1.0-SNAPSHOT
```

then for ReactorReader, in theory, you don't need to invoke it since it has been injected in Aether RepositorySession: http://maven.apache.org/ref/3.0.5/maven-core/xref/org/apache/maven/DefaultMaven.html#247
so I'd expect Aether to find it: need to investigate why it is not found

**Comment by william-ferguson-au** [comment]
I wouldn't worry about checking the multi-module-plugin log output. The plugin is not what is being verified. The log was just there for confirmation when building and testing this.

WRT ReactorReader it seems that has changed quite a bit in 3.2.1. It appears to have been replaced by org.eclipse.aether.repository.WorkspaceReader

**Comment by hboutemy** [comment]
IIUC, I can delete the multi-module-plugin, which isn't necessary to the IT

WRT ReactorReader, I didn't precisely study its evolutions: I'm just figuring out its objective for reactor resolution

**Comment by william-ferguson-au** [comment]
> IIUC, I can delete the multi-module-plugin, which isn't necessary to the IT

No, as I explained before it is needed to exercise the IT. It is there to
verify that the dependencies are available prior to any artifacts being
built.

**Comment by hboutemy** [comment]
I really don't understand how it is needed if you don't check any result from it
deactivating its execution from module-z-deps-y doesn't change anything

**Comment by william-ferguson-au** [comment]
> deactivating its execution from module-z-deps-y doesn't change anything

:-) Yes it does. 

Deactivating it in module-z-deps-y means that you are not exercising the test.
Ie you are running an empty test suite.

**Comment by hboutemy** [comment]
ok, I hardened the checks to ensure what is really tested (which is not what I expected)

**Pull request closed without merging**
